// scripts/buildAssetMap.mjs
import fs from "fs";
import path from "path";
import url from "url";

const ROOT = process.cwd();
const JSON_PATH = path.join(ROOT, "assets", "data", "data.json");
const ARGS = new Set(process.argv.slice(2));
const DRY_RUN = ARGS.has("--dry-run") && !ARGS.has("--force") ? true : !ARGS.has("--force"); // за замовчуванням dry-run
const ASSETS_DIR = path.join(ROOT, "assets");
const ING_DIR = path.join(ASSETS_DIR, "ingredients");
const CKT_DIR = path.join(ASSETS_DIR, "cocktails");
const OUT_FILE = path.join(ROOT, "scripts", "assetMap.js");

const IMG_EXTS = new Set([".png", ".jpg", ".jpeg"]);

// ---------------- helpers ----------------
function isImage(file) {
  const ext = path.extname(file).toLowerCase();
  return IMG_EXTS.has(ext);
}

/**
 * Повертає відносний шлях у вигляді 'assets/...'
 * з різних форматів photoUri (unstable_path, прямий шлях у assets, тощо).
 * Якщо шлях не веде в /assets, повертає null.
 */
function extractAssetsRelPath(photoUri) {
  if (!photoUri || typeof photoUri !== "string") return null;

  // Випадок 1: URL з параметром unstable_path=.%2Fassets%2F...
  try {
    const maybeUrl = new url.URL(photoUri);
    const up = maybeUrl.searchParams.get("unstable_path");
    if (up) {
      const decoded = decodeURIComponent(up); // типово './assets/...'
      const cleaned = decoded.replace(/^\.?\//, ""); // прибираємо './' або '/'
      if (cleaned.startsWith("assets/")) return cleaned;
    }
  } catch (_) {
    // не URL — впадемо нижче
  }

  // Випадок 2: вже відносний шлях до assets
  if (photoUri.startsWith("./assets/") || photoUri.startsWith("/assets/") || photoUri.startsWith("assets/")) {
    const cleaned = photoUri.replace(/^\.?\//, "");
    return cleaned.startsWith("assets/") ? cleaned : null;
  }

  // Тимчасові шляхи (file://...) ігноруємо
  return null;
}

/** Витягує всі валідні assets-шляхи з photoUri в масиві об’єктів */
function collectFromArray(arr) {
  const out = new Set();
  for (const item of arr || []) {
    const rel = extractAssetsRelPath(item?.photoUri);
    if (rel) out.add(rel);
  }
  return out;
}

/** Рекурсивно збирає всі зображення з папки dir, повертає шляхи у форматі 'assets/...' */
function collectImagesRecursively(dir, relBase = "assets") {
  const res = new Set();
  if (!fs.existsSync(dir)) return res;

  for (const entry of fs.readdirSync(dir)) {
    const abs = path.join(dir, entry);
    const st = fs.statSync(abs);
    if (st.isDirectory()) {
      for (const p of collectImagesRecursively(abs, path.posix.join(relBase, path.basename(dir), entry))) {
        res.add(p);
      }
    } else if (st.isFile() && isImage(entry)) {
      // Вирахуємо відносний шлях 'assets/...'
      const rel = path.posix.join(
        "assets",
        path.relative(ASSETS_DIR, abs).split(path.sep).join(path.posix.sep)
      );
      res.add(rel);
    }
  }
  return res;
}

/** Збирає всі зображення з кореня assets/ (лише перший рівень) */
function collectFromAssetsRoot() {
  const out = new Set();
  if (!fs.existsSync(ASSETS_DIR)) return out;
  for (const file of fs.readdirSync(ASSETS_DIR)) {
    const full = path.join(ASSETS_DIR, file);
    const stat = fs.statSync(full);
    const lower = file.toLowerCase();
    if (stat.isFile() && isImage(lower)) {
      out.add(path.posix.join("assets", file));
    }
  }
  return out;
}

/** Перевіряє існування файлу; якщо нема — лог warning і пропускає */
function filterExisting(relPaths) {
  const out = [];
  for (const rel of relPaths) {
    const abs = path.join(ROOT, rel);
    if (fs.existsSync(abs)) out.push(rel);
    else console.warn(`⚠ Відсутній файл: ${rel}`);
  }
  return out;
}

function buildMapObject(relPaths) {
  const sorted = [...relPaths].sort((a, b) => a.localeCompare(b));
  const lines = sorted.map((rel) => `  '${rel}': require('../${rel}'),`);
  const header = `/* ⚠️ AUTOGENERATED FILE – do not edit by hand.
   * Generated by scripts/buildAssetMap.mjs
   * Run with:
   *   node scripts/buildAssetMap.mjs [--dry-run|--force]
   */`;
  const body = `export const ASSET_MAP = {\n${lines.join("\n")}\n};\n`;
  return `${header}\n\n${body}`;
}

function ensureDirs() {
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
}

/** Видаляє файли з масиву шляхів 'assets/...' (відносно кореня), з логами і dry-run */
function removeFiles(relPaths) {
  let removed = 0;
  for (const rel of relPaths) {
    const abs = path.join(ROOT, rel);
    if (!abs.startsWith(ASSETS_DIR)) {
      console.warn(`⚠ Пропущено (не в assets): ${rel}`);
      continue;
    }
    if (DRY_RUN) {
      console.log(`DRY-RUN: видалив би ${rel}`);
    } else {
      try {
        fs.unlinkSync(abs);
        removed++;
        console.log(`🗑 Видалено: ${rel}`);
      } catch (e) {
        console.warn(`⚠ Не вдалося видалити ${rel}: ${e.message}`);
      }
    }
  }
  if (DRY_RUN) {
    console.log(`DRY-RUN: всього файлів до видалення: ${relPaths.length}`);
  } else {
    console.log(`✔ Видалено файлів: ${removed}/${relPaths.length}`);
  }
}

// ---------------- main ----------------
function main() {
  if (!fs.existsSync(JSON_PATH)) {
    console.error(`❌ Не знайдено JSON: ${JSON_PATH}`);
    process.exit(1);
  }

  const raw = fs.readFileSync(JSON_PATH, "utf8");
  let data;
  try {
    data = JSON.parse(raw);
  } catch (e) {
    console.error("❌ Помилка парсингу JSON:", e.message);
    process.exit(1);
  }

  // 1) Збираємо посилання на зображення з JSON
  const referenced = new Set();
  if (Array.isArray(data.ingredients)) {
    for (const p of collectFromArray(data.ingredients)) referenced.add(p);
  }
  if (Array.isArray(data.cocktails)) {
    for (const p of collectFromArray(data.cocktails)) referenced.add(p);
  }

  // 2) Додаємо PNG/JPG/JPEG з кореня assets/ (іконки, splash тощо)
  for (const p of collectFromAssetsRoot()) referenced.add(p);

  // 3) Фільтруємо по наявності
  const existingReferenced = new Set(filterExisting(referenced));

  // 4) Будуємо та записуємо assetMap.js
  const outJs = buildMapObject(existingReferenced);
  ensureDirs();
  fs.writeFileSync(OUT_FILE, outJs, "utf8");
  console.log(`✔ Оновлено ${path.relative(ROOT, OUT_FILE)} (${existingReferenced.size} записів)`);

  // 5) Пошук невикористаних файлів у assets/cocktails та assets/ingredients
  const allInCocktails = collectImagesRecursively(CKT_DIR);
  const allInIngredients = collectImagesRecursively(ING_DIR);

  const referencedInCocktails = [...existingReferenced].filter(p => p.startsWith("assets/cocktails/"));
  const referencedInIngredients = [...existingReferenced].filter(p => p.startsWith("assets/ingredients/"));

  const unusedCocktails = [...allInCocktails].filter(p => !referencedInCocktails.includes(p));
  const unusedIngredients = [...allInIngredients].filter(p => !referencedInIngredients.includes(p));

  // 6) Видалення невикористаних
  if (unusedCocktails.length === 0 && unusedIngredients.length === 0) {
    console.log("✔ Невикористаних файлів у assets/cocktails та assets/ingredients не знайдено.");
  } else {
    console.log(`Зайві файли (всього ${unusedCocktails.length + unusedIngredients.length}):`);
    for (const p of [...unusedIngredients, ...unusedCocktails]) console.log(`  - ${p}`);

    removeFiles([...unusedIngredients, ...unusedCocktails]);
  }

  if (DRY_RUN) {
    console.log("ℹ Запустіть з --force, щоб застосувати видалення.");
  }
}

main();
